/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum RouterMap {
  // 首页
  Home_Page = 'HomePage',
  // 搜索页面
  QuestionSearch_Page = 'SearchPage',
  // 考试答题页面
  AnswerQuestionsTwo_Page = 'AnswerQuestionsTwoPage',
  // 评分页面
  ExamResultPage_Page = 'ExamResultPage',
  // 训练答题页面
  AnswerQuestions_Page = 'AnswerQuestionsPage',
  // 测试报告页面
  TestReportPage = 'TestReportPage',
  // 我的笔记页面
  MyNotesPage = 'MyNotesPage',
  // 查看笔记页面
  ViewNotePage = 'ViewNotePage',
  // 练习记录页面
  PracticeRecordsPage = 'PracticeRecordsPage',
  // 练习明细页面
  PracticeDetailsPage = 'PracticeDetailsPage',
  // 某一天练习记录页面
  OneDayPracticeRecordsPage = 'OneDayPracticeRecordsPage',
  // 资料下载页
  MaterialDownload = 'MaterialDownload',
  // 课程详情页面
  CourseIntroductionPage = 'CourseIntroductionPage',
  // 我的错题页面
  MyWrongPage = 'MyWrongPage',
  // 我的收藏页面
  MyCollectionPage = 'MyCollectionPage',
  // 浏览记录页面
  BrowsingHistoryPage = 'BrowsingHistoryPage',
  // 精选课程详情页
  GoodCourseDetailPage = 'GoodCourseDetailPage',
  // 章节练习页面
  ChapterPractice = 'ChapterPractice',
  // 模拟试卷/全真试卷
  MockTestPage = 'MockTestPage',
  // 订单详情页
  OrderDetailPage = 'OrderDetailPage',
  // 登录
  QuickLoginPage = 'QuickLoginPage',

}