/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class PreferConstant {
  // 题库模板
  static readonly EXAMPREFER: string = 'EXAMPREFER';
  // 练习记录
  static readonly PRACTICE_RECORDS: string = 'PRACTICE_RECORDS';
  // 浏览课程历史记录
  static readonly EXAMPREFER_KCJL: string = 'EXAMPREFER_KCJL';
  // 题目笔记
  static readonly TOPIC_NOTES: string = 'TOPIC_NOTES';
  // 错题记录
  static readonly EXAMPREFER_CTJL: string = 'EXAMPREFER_CTJL';
  // 收藏记录
  static readonly EXAMPREFER_COLLECT: string = 'EXAMPREFER_COLLECT';
  //意见反馈记录
  static readonly FEEDBACK_RECORD: string = 'FEEDBACK_RECORD';
  //首次进入启动页隐私协议状态
  static readonly IS_FIRST: string = 'IS_FIRST';
}